### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by jamescook** [spree/deface#89]
I was looking at working on Rails 4 compatibility, but I'm seeing a few errors like below in master. My ruby version string is "ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-darwin10.8.0]"

```
  1) Deface::TemplateHelper load_template_source with overrides defined should return overridden source for partial including overrides
 Failure/Error: load_template_source("shared/post", true).should == "\n<%= \"And I've got ERB\" %>"
   expected: "\n<%= \"And I've got ERB\" %>"
        got: "\n<%= \"And I've got ERB\" %>\n" (using ==)
   Diff:
 # ./spec/deface/template_helper_spec.rb:53:in `block (4 levels) in <module:Deface>'
```
